version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - ../.env/.env.postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -u postgres -d postgres"
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
