version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - ../.env/.env.postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER}"
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  kafka:
    depends_on:
      postgres:
        condition: service_healthy
    image: apache/kafka:3.7.1
    ports:
      - "9092:9092"

volumes:
  postgres:
