linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

  disable:
    - forbidigo
    - exhaustivestruct
    - deadcode
    - golint
    - varcheck
    - scopelint
    - structcheck
    - interfacer
    - nosnakecase
    - maligned
    - ifshort
    - tagalign
    - godot

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - "github.com/Vilinvil/task_messaggio"
          - "github.com/go-park-mail-ru/2023_2_Rabotyagi"
          - "github.com/google/uuid"
          - "github.com/jackc/pgx/v5"
          - "github.com/jackc/pgx/v5/pgxpool"
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  varnamelen:
    min-name-length: 3
    ignore-decls:
      - t *testing.T
      - tx pgx.Tx
      - w http.ResponseWriter
      - r *http.Request
      - r io.Reader
