// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB7d666c2DecodeGithubComVilinvilTaskMessaggioPkgModels(in *jlexer.Lexer, out *MessageStatistic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "total":
			out.Total = int(in.Int())
		case "handled":
			out.Handled = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB7d666c2EncodeGithubComVilinvilTaskMessaggioPkgModels(out *jwriter.Writer, in MessageStatistic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"handled\":"
		out.RawString(prefix)
		out.Int(int(in.Handled))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageStatistic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB7d666c2EncodeGithubComVilinvilTaskMessaggioPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageStatistic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB7d666c2EncodeGithubComVilinvilTaskMessaggioPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageStatistic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB7d666c2DecodeGithubComVilinvilTaskMessaggioPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageStatistic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB7d666c2DecodeGithubComVilinvilTaskMessaggioPkgModels(l, v)
}
